"""Tests for migration_preflight.py — Steps 0–4 detection (no human decisions)."""

import datetime
import os

import migration_preflight as pf

CONFIG = 'project:\n  prefix: "PRJ"\n'


def setup_project(tmp_path):
    (tmp_path / "iconix.config.yaml").write_text(CONFIG, encoding="utf-8")
    for d in ("use-cases", "robustness", "sequence", "class-model",
              "use-case-packages", "domain-model", "migration"):
        (tmp_path / d).mkdir(parents=True, exist_ok=True)
    return str(tmp_path / "iconix.config.yaml"), str(tmp_path / "migration")


def touch(path, text="x"):
    path.write_text(text, encoding="utf-8")


def set_mtime_date(path, iso_date):
    ts = datetime.datetime.fromisoformat(iso_date + "T12:00:00").timestamp()
    os.utime(path, (ts, ts))


# ── Step 0: greenfield ─────────────────────────────────────────────────────
def test_greenfield_detected_and_aborts(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "use-cases" / "PRJ-UC-001-checkout.md")
    r = pf.run_preflight("", cfg, mig)
    assert r["greenfield_detected"] is True
    assert r["abort_greenfield"] is True
    assert any("PRJ-UC-001-checkout.md" in f for f in r["greenfield_files"])


def test_allow_greenfield_disables_abort(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "use-cases" / "PRJ-UC-001-checkout.md")
    r = pf.run_preflight("--allow-greenfield", cfg, mig)
    assert r["greenfield_detected"] is True
    assert r["allow_greenfield"] is True
    assert r["abort_greenfield"] is False


def test_draft_is_not_greenfield(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md")
    r = pf.run_preflight("", cfg, mig)
    assert r["greenfield_detected"] is False


def test_class_model_draft_stamp(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "class-model" / "class-model.puml",
          "' DRAFT — generated by iconix-migration\n@startuml\n@enduml\n")
    r = pf.run_preflight("", cfg, mig)
    # DRAFT-stamped class model is NOT greenfield, but IS a regenerable draft.
    assert r["greenfield_detected"] is False
    assert any("class-model.puml" in p for p in r["safe_to_regenerate"])


def test_class_model_no_stamp_is_greenfield(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "class-model" / "class-model.puml", "@startuml\n@enduml\n")
    r = pf.run_preflight("", cfg, mig)
    assert r["greenfield_detected"] is True


# ── Steps 2–4: promoted / human-edited / safe ──────────────────────────────
def test_promoted_slug_excluded_from_safe(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md")
    touch(tmp_path / "ids.registry.md",
          "| ID | Slug | Path | Note |\n|---|---|---|---|\n"
          "| PRJ-UC-001 | checkout | use-cases/PRJ-UC-001-checkout.md | promoted |\n")
    r = pf.run_preflight("", cfg, mig)
    assert {"id": "PRJ-UC-001", "slug": "checkout"} in r["promoted_artifacts"]
    assert not any("checkout" in p for p in r["safe_to_regenerate"])


def test_human_edited_draft_flagged(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "migration" / "checkpoint-2026-05-01.json", "{}")
    draft = tmp_path / "use-cases" / "UC-DRAFT-002-payment.md"
    touch(draft)
    set_mtime_date(draft, "2026-05-15")  # edited after the 2026-05-01 run
    r = pf.run_preflight("", cfg, mig)
    assert r["last_run_date"] == "2026-05-01"
    assert any("UC-DRAFT-002-payment.md" in p for p in r["human_edited_drafts"])
    assert not any("payment" in p for p in r["safe_to_regenerate"])


def test_unedited_draft_is_safe(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "migration" / "checkpoint-2026-05-01.json", "{}")
    draft = tmp_path / "use-cases" / "UC-DRAFT-003-search.md"
    touch(draft)
    set_mtime_date(draft, "2026-05-01")  # same day as run → not edited
    r = pf.run_preflight("", cfg, mig)
    assert any("UC-DRAFT-003-search.md" in p for p in r["safe_to_regenerate"])


def test_nothing_left_to_migrate(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md")
    touch(tmp_path / "ids.registry.md",
          "| ID | Slug |\n|---|---|\n| PRJ-UC-001 | checkout |\n")
    r = pf.run_preflight("", cfg, mig)
    assert r["nothing_left_to_migrate"] is True


def test_no_drafts_is_not_nothing_left(tmp_path):
    cfg, mig = setup_project(tmp_path)
    r = pf.run_preflight("", cfg, mig)
    assert r["nothing_left_to_migrate"] is False


# ── Step 4b: DB readiness ──────────────────────────────────────────────────
def test_db_warning_when_schema_and_scope_no_glossary(tmp_path):
    cfg, mig = setup_project(tmp_path)
    (tmp_path / "db").mkdir()
    touch(tmp_path / "db" / "schema.sql", "CREATE TABLE x();")
    r = pf.run_preflight("--scope OrderService", cfg, mig)
    assert r["scope"] == "OrderService"
    assert r["schema_files_present"] is True
    assert r["db_readiness_warning"] is True


def test_db_warning_suppressed_by_glossary(tmp_path):
    cfg, mig = setup_project(tmp_path)
    (tmp_path / "db").mkdir()
    touch(tmp_path / "db" / "schema.sql", "CREATE TABLE x();")
    touch(tmp_path / "migration" / "domain-glossary.md", "# glossary")
    r = pf.run_preflight("--scope OrderService", cfg, mig)
    assert r["domain_glossary_exists"] is True
    assert r["db_readiness_warning"] is False


def test_no_scope_no_db_warning(tmp_path):
    cfg, mig = setup_project(tmp_path)
    (tmp_path / "db").mkdir()
    touch(tmp_path / "db" / "schema.sql", "CREATE TABLE x();")
    r = pf.run_preflight("", cfg, mig)
    assert r["db_readiness_warning"] is False  # warning only for scoped runs


def test_parse_scope_quoted():
    assert pf.parse_scope('--scope "Order Service" --max-uc 5') == "Order Service"
    assert pf.parse_scope("--scope OrderService") == "OrderService"
    assert pf.parse_scope("--max-uc 5") is None


# ── review fix (HIGH): incremental run must not flag its own promoted outputs ─
def test_promoted_artifact_not_greenfield_on_incremental(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "migration" / "checkpoint-2026-05-01.json", "{}")  # prior run
    touch(tmp_path / "use-cases" / "PRJ-UC-001-checkout.md")
    touch(tmp_path / "ids.registry.md",
          "| ID | Slug | Path | Note |\n|---|---|---|---|\n"
          "| PRJ-UC-001 | checkout | use-cases/PRJ-UC-001-checkout.md | promoted |\n")
    r = pf.run_preflight("", cfg, mig)
    assert r["greenfield_detected"] is False
    assert r["abort_greenfield"] is False


def test_promoted_class_model_not_greenfield_on_incremental(tmp_path):
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "migration" / "checkpoint-2026-05-01.json", "{}")  # prior run
    # class-model.puml with its DRAFT stamp stripped (post-promotion) — no-ID artifact
    touch(tmp_path / "class-model" / "class-model.puml", "@startuml\nclass Order\n@enduml\n")
    r = pf.run_preflight("", cfg, mig)
    assert r["greenfield_detected"] is False


def test_fresh_target_still_flags_greenfield(tmp_path):
    # no prior run, empty registry → a non-DRAFT UC IS a real hand-authored collision
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "use-cases" / "PRJ-UC-001-checkout.md")
    r = pf.run_preflight("", cfg, mig)
    assert r["greenfield_detected"] is True


def test_unpromoted_artifact_still_greenfield_on_incremental(tmp_path):
    # a prior run exists, but a UC that is NOT in the registry is still a collision
    cfg, mig = setup_project(tmp_path)
    touch(tmp_path / "migration" / "checkpoint-2026-05-01.json", "{}")
    touch(tmp_path / "use-cases" / "PRJ-UC-050-handauthored.md")  # not in registry
    r = pf.run_preflight("", cfg, mig)
    assert r["greenfield_detected"] is True
