"""Tests for promote.py — the [VERIFY] gate, xref word-boundary, Source-container, dry-run.

Most tests call promote.promote() directly (it returns the result dict and performs the
file mutations), which avoids parsing the multiple JSON objects main() prints. Exit-code
behaviour is covered by the two main() tests at the end.
"""

import promote
import ids
import _common

CONFIG = 'project:\n  prefix: "PRJ"\n'


def setup_project(tmp_path):
    (tmp_path / "iconix.config.yaml").write_text(CONFIG, encoding="utf-8")
    for d in ("use-cases", "robustness", "sequence", "class-model",
              "use-case-packages", "domain-model"):
        (tmp_path / d).mkdir(parents=True, exist_ok=True)
    return str(tmp_path / "iconix.config.yaml")


def uc(slug_id, body=""):
    return f"# UC: {slug_id}\n**ID:** {slug_id}\n\n## Traceability\nUpstream: REQ-001\n\n{body}\n"


# ── THE critical test: [VERIFY:HIGH] must skip ──────────────────────────────
def test_verify_high_skipped(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(
        uc("UC-DRAFT-001", "Precondition: cart valid [VERIFY:HIGH]"), encoding="utf-8")
    r = promote.promote("all", cfg, dry_run=False)
    assert any("UC-DRAFT-001" in s["file"] for s in r["skipped_verify"])
    assert r["promoted"] == []
    assert (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").exists()  # untouched


def test_verify_plain_and_emdash_skipped(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "use-cases" / "UC-DRAFT-001-a.md").write_text(
        uc("UC-DRAFT-001", "x [VERIFY] y"), encoding="utf-8")
    (tmp_path / "use-cases" / "UC-DRAFT-002-b.md").write_text(
        uc("UC-DRAFT-002", "x [VERIFY — confirm with PO] y"), encoding="utf-8")
    r = promote.promote("all", cfg, dry_run=False)
    skipped = {s["file"] for s in r["skipped_verify"]}
    assert any("UC-DRAFT-001" in f for f in skipped)
    assert any("UC-DRAFT-002" in f for f in skipped)


# ── clean promotion ─────────────────────────────────────────────────────────
def test_clean_draft_promoted_and_registered(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(uc("UC-DRAFT-001"), encoding="utf-8")
    r = promote.promote("all", cfg, dry_run=False)
    assert r["promoted"][0]["new_id"] == "PRJ-UC-001"
    assert (tmp_path / "use-cases" / "PRJ-UC-001-checkout.md").exists()
    assert not (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").exists()
    promoted = (tmp_path / "use-cases" / "PRJ-UC-001-checkout.md").read_text(encoding="utf-8")
    assert "**ID:** PRJ-UC-001" in promoted
    assert "UC-DRAFT-001" not in promoted
    rows = ids.read_rows(str(tmp_path / "ids.registry.md"))
    assert any(row["id"] == "PRJ-UC-001" and row["slug"] == "checkout" for row in rows)


def test_id_continues_from_registry_high(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "ids.registry.md").write_text(
        "| ID | Slug |\n|---|---|\n| PRJ-UC-006 | cart |\n", encoding="utf-8")
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(uc("UC-DRAFT-001"), encoding="utf-8")
    promote.promote("all", cfg, dry_run=False)
    assert (tmp_path / "use-cases" / "PRJ-UC-007-checkout.md").exists()


# ── xref word boundary: UC-DRAFT-1 must not corrupt UC-DRAFT-10 ─────────────
def test_xref_word_boundary(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "use-cases" / "UC-DRAFT-1-a.md").write_text(
        uc("UC-DRAFT-1", "Related: UC-DRAFT-10 follows this."), encoding="utf-8")
    (tmp_path / "use-cases" / "UC-DRAFT-10-b.md").write_text(uc("UC-DRAFT-10"), encoding="utf-8")
    promote.promote("all", cfg, dry_run=False)
    a = (tmp_path / "use-cases" / "PRJ-UC-001-a.md").read_text(encoding="utf-8")
    assert "**ID:** PRJ-UC-001" in a
    assert "Related: PRJ-UC-002 follows this." in a   # UC-DRAFT-10 → PRJ-UC-002, intact
    assert "PRJ-UC-0010" not in a                     # not corrupted
    assert (tmp_path / "use-cases" / "PRJ-UC-002-b.md").exists()


# ── Source-container preserved verbatim ─────────────────────────────────────
def test_source_container_preserved(tmp_path):
    cfg = setup_project(tmp_path)
    sc = "<!-- Source-container: OrderService @ ../order-service/src/ -->"
    content = ("' DRAFT — generated by iconix-migration on 2026-05-30\n"
               + sc + "\n" + uc("UC-DRAFT-001"))
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(content, encoding="utf-8")
    promote.promote("all", cfg, dry_run=False)
    promoted = (tmp_path / "use-cases" / "PRJ-UC-001-checkout.md").read_text(encoding="utf-8")
    assert sc in promoted                          # Source-container byte-identical
    assert "DRAFT — generated by" not in promoted  # stamp removed


def test_multi_container_detected(tmp_path):
    cfg = setup_project(tmp_path)
    content = ("<!-- Source-container: Frontend @ ../fe/src/, Backend @ ../be/src/ -->\n"
               + uc("UC-DRAFT-001"))
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(content, encoding="utf-8")
    r = promote.promote("all", cfg, dry_run=False)
    assert any(m["new_id"] == "PRJ-UC-001" and len(m["containers"]) == 2
               for m in r["multi_container"])


# ── class-model DRAFT stamp ─────────────────────────────────────────────────
def test_class_model_keeps_name_drops_stamp(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "class-model" / "class-model.puml").write_text(
        "' DRAFT — generated by iconix-migration on 2026-05-30\n@startuml\nclass Order\n@enduml\n",
        encoding="utf-8")
    promote.promote("all", cfg, dry_run=False)
    cm = tmp_path / "class-model" / "class-model.puml"
    assert cm.exists()  # name unchanged
    assert "DRAFT" not in cm.read_text(encoding="utf-8")


# ── already promoted by slug ────────────────────────────────────────────────
def test_already_promoted_slug_skipped(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "ids.registry.md").write_text(
        "| ID | Slug |\n|---|---|\n| PRJ-UC-001 | checkout |\n", encoding="utf-8")
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(uc("UC-DRAFT-001"), encoding="utf-8")
    r = promote.promote("all", cfg, dry_run=False)
    assert any(s["slug"] == "checkout" for s in r["skipped_already"])
    assert r["promoted"] == []


# ── dry-run mutates nothing ─────────────────────────────────────────────────
def test_dry_run_no_mutation(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(uc("UC-DRAFT-001"), encoding="utf-8")
    r = promote.promote("all", cfg, dry_run=True)
    assert r["promoted"][0]["new_id"] == "PRJ-UC-001"  # planned
    assert (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").exists()
    assert not (tmp_path / "use-cases" / "PRJ-UC-001-checkout.md").exists()
    assert not (tmp_path / "ids.registry.md").exists()


# ── main() exit codes ───────────────────────────────────────────────────────
def run(argv):
    try:
        return promote.main(argv)
    except SystemExit as exc:
        return exc.code


def test_main_exit_0_on_success(tmp_path):
    cfg = setup_project(tmp_path)
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(uc("UC-DRAFT-001"), encoding="utf-8")
    assert run(["--args", "all", "--config", cfg]) == _common.EXIT_OK


def test_main_exit_1_when_nothing_eligible(tmp_path):
    cfg = setup_project(tmp_path)
    assert run(["--args", "all", "--config", cfg]) == _common.EXIT_GATE


# ── review fix: Source-container with "DRAFT" in the container name survives ─
def test_source_container_with_draft_in_name_preserved(tmp_path):
    cfg = setup_project(tmp_path)
    sc = "<!-- Source-container: DRAFTService @ ../draft-svc/src/ -->"
    content = ("' DRAFT — generated by iconix-migration on 2026-05-30\n"
               + sc + "\n" + uc("UC-DRAFT-001"))
    (tmp_path / "use-cases" / "UC-DRAFT-001-checkout.md").write_text(content, encoding="utf-8")
    promote.promote("all", cfg, dry_run=False)
    promoted = (tmp_path / "use-cases" / "PRJ-UC-001-checkout.md").read_text(encoding="utf-8")
    assert sc in promoted                          # preserved despite 'DRAFT' in name
    assert "DRAFT — generated by" not in promoted  # stamp still removed
