# features/<PREFIX>-UC-XXX-<slug>.feature
# Traceability: <PREFIX>-UC-XXX
# Generated by: iconix-tester
# TCs covered: <PREFIX>-TC-XXX (basic course), <PREFIX>-TC-YYY (alt-A: <name>)
#              one line per acceptance-bdd TC for this UC

Feature: <feature name — matches the UC title exactly>
  As a <specific role — matches the UC actor>
  I want <observable outcome — not a solution or implementation detail>
  So that <business benefit — matches the UC goal statement>

  Background:
    Given <shared precondition true for every scenario in this file>
    And <shared precondition>
    # Remove Background if no preconditions are common to all scenarios

  # <PREFIX>-TC-XXX — basic course
  Scenario: <happy-path name>
    Given <actor or system state specific to this scenario>
    And <additional precondition if needed>
    When <actor> <action verb> <object>
    Then <observable system response>
    And <observable system response>

  # <PREFIX>-TC-YYY — alt-A: <branch name>
  Scenario: <alternate course name>
    Given <precondition that triggers the alternate>
    When <actor> <action verb> <object>
    Then <observable failure or branch response>
    And <observable recovery or message>

  # Add one Scenario block per alternate-course TC (alt-B, alt-C, …)
  # Edge-case TCs with type acceptance-bdd also go here, after the course Scenarios

  # ── Scenario Outline — optional, for data-driven alternates only ─────────────
  # Use when the same step sequence repeats across a small, finite set of input
  # variants. Keep Examples tables narrow (≤ 4 columns); wide tables reduce
  # readability at stakeholder sign-off ceremonies.
  #
  # # <PREFIX>-TC-ZZZ — alt-B: <parametric name>
  # Scenario Outline: <parametric scenario name>
  #   Given the <actor> has role "<role>"
  #   When they submit <amount> for <purpose>
  #   Then the system responds with "<outcome>"
  #
  #   Examples:
  #     | role   | amount | purpose  | outcome           |
  #     | admin  | 100.00 | transfer | order confirmed   |
  #     | viewer | 100.00 | transfer | permission denied |
  # ─────────────────────────────────────────────────────────────────────────────
